spring:
  application:
    name: foody

  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.hejuuzsabiddvwkgxoej
    password: tepmad-6pahPu-hidfox
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'foodydeliveryapp@gmail.com'
    password: 'regwsvilfxnmcyoz'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

foody:
  security:
    jwt:
      secret: your-super-long-foody-jwt-secret-change-this-in-production-123456
      expiration-ms: 86400000
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME:}}
